Repository kyaukyuai/gpt-all-star, pull requests merged in 2024-03, with the labels that each got.

#138 Update release drafter permissions in workflows
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: feature

#140 Add commitish parameter for release-drafter action
  .github/workflows/release-drafter.yml
Labels: bug

#142 Add Python Semantic Release for versioning and publishing
  .github/workflows/publish.yml
  poetry.lock
  pyproject.toml
Labels: feature

#148 Update name and tag templates to include 'v' prefix
  .github/release-drafter.yml
Labels: bug

#153 Add release workflow for Python package publication
  .github/workflows/publish.yml
  .github/workflows/release.yml
Labels: feature

#159 Update version to 0.0.5 and exclude dirs in file search
  gpt_all_star/core/storage.py
  gpt_all_star/helper/git.py
  pyproject.toml
Labels: refactor

#163 Feat/UI
  gpt_all_star/__init__.py
  gpt_all_star/core/gpt_all_star.py
  gpt_all_star/core/project.py
  gpt_all_star/core/steps/development/development.py
  gpt_all_star/core/steps/entrypoint/entrypoint.py
  gpt_all_star/core/steps/healing/healing.py
  gpt_all_star/core/steps/improvement/improvement.py
  gpt_all_star/core/steps/specification/specification.py
  gpt_all_star/core/steps/step.py
  gpt_all_star/core/steps/system_design/system_design.py
  gpt_all_star/core/steps/ui_design/ui_design.py
  poetry.lock
  pyproject.toml
Labels: feature

#166 add translate logic and po, mo files
  gpt_all_star/core/agents/agent.py
  gpt_all_star/core/agents/copilot.py
  gpt_all_star/core/deployment/deployment.py
  gpt_all_star/core/execution/execution.py
  gpt_all_star/core/project.py
  gpt_all_star/core/steps/development/development.py
  gpt_all_star/core/steps/entrypoint/entrypoint.py
  gpt_all_star/core/steps/healing/healing.py
  gpt_all_star/core/steps/improvement/improvement.py
  gpt_all_star/core/steps/specification/specification.py
  gpt_all_star/core/steps/step.py
  gpt_all_star/core/steps/system_design/system_design.py
  gpt_all_star/core/steps/ui_design/ui_design.py
  gpt_all_star/core/team.py
  gpt_all_star/helper/translator.py
  gpt_all_star/locales/ja_JP/LC_MESSAGES/messages.mo
  gpt_all_star/locales/ja_JP/ja.po
Labels: feature

#175 Simplify code-check for better readability
  Makefile
Labels: bug

#176 Fix/gpt all star
  gpt_all_star/core/project.py
Labels: bug

#178 Add MkDocs deployment workflow for GitHub Pages
  .github/workflows/mkdocs.yml
Labels: feature

#181 Update Python version to '3.10' in workflow
  .github/workflows/mkdocs.yml
Labels: bug

#182 Refactor creating human message with task information
  gpt_all_star/core/message.py
  gpt_all_star/core/project.py
  poetry.lock
Labels: bug

#183 Bump version to 0.0.11 in pyproject.toml
  pyproject.toml
Labels: bug

#187 Refactor exception handling for step execution
  gpt_all_star/core/project.py
Labels: bug

#193 Update Azure OpenAI API version and LLM creation logic
  .env.sample
  gpt_all_star/core/agents/agent.py
  gpt_all_star/core/agents/chain.py
  gpt_all_star/core/llm.py
Labels: feature

#194 Bump version to 0.0.12 in pyproject.toml
  pyproject.toml
Labels: feature

#199 chore: 🤖 versionup
  poetry.lock
Labels: feature

#200 Bump version to 0.0.13 and add langchain-anthropic dep
  poetry.lock
  pyproject.toml
Labels: bug

#202 Refactor agent retrieval by role, improve agent assignment
  gpt_all_star/core/agents/agents.py
  gpt_all_star/core/agents/chain.py
  gpt_all_star/core/project.py
  gpt_all_star/core/team.py
  gpt_all_star/helper/multi_agent_collaboration_graph.py
  pyproject.toml
Labels: bug

#203 Update supervisor name attribute to role name in message creation
  gpt_all_star/core/project.py
Labels: chore

#206 Bump version to 0.0.15 in pyproject.toml
  pyproject.toml
Labels: chore

#207 Add execute method to Project class for application execution
  gpt_all_star/core/gpt_all_star.py
  gpt_all_star/core/project.py
Labels: feature

#208 Bump version to 0.0.16 in pyproject.toml
  pyproject.toml
Labels: chore

#214 Add optional display parameter to run_command method
  gpt_all_star/core/agents/copilot.py
  gpt_all_star/core/execution/execution.py
  gpt_all_star/core/project.py
Labels: feature

#215 Bump version to 0.0.17 in pyproject.toml
  pyproject.toml
Labels: chore

#218 Add new benchmark files
  benchmarks/BENCHMARKS.md
  benchmarks/SWE-bench.md
Labels: documentation, chore

#220 Refactor message creation with execution info
  gpt_all_star/core/project.py
Labels: feature

#221 Bump version to 0.0.18 in pyproject.toml
  pyproject.toml
Labels: chore

#222 Update Specification class by removing japanese_mode
  gpt_all_star/core/steps/specification/specification.py
Labels: chore

#224 Remove unused code and clean up main function
  gpt_all_star/main.py
Labels: feature

#225 Bump version to 0.0.19 in pyproject.toml
  pyproject.toml
Labels: chore

#226 Add UI project details to README and docs
  README.md
  docs/index.md
Labels: documentation, chore

#227 Update improvement options for project steps
  README.md
  gpt_all_star/core/gpt_all_star.py
  gpt_all_star/core/respond.py
  gpt_all_star/core/steps/development/development.py
  gpt_all_star/core/steps/development/improvement_prompt.py
  gpt_all_star/core/steps/doc_improvement/__init__.py
  gpt_all_star/core/steps/doc_improvement/doc_improvement.py
  gpt_all_star/core/steps/entrypoint/entrypoint.py
  gpt_all_star/core/steps/healing/healing.py
  gpt_all_star/core/steps/improvement/__init__.py
  gpt_all_star/core/steps/improvement/improvement.py
  gpt_all_star/core/steps/specification/improvement_prompt.py
  gpt_all_star/core/steps/specification/specification.py
  gpt_all_star/core/steps/step.py
  gpt_all_star/core/steps/steps.py
  gpt_all_star/core/steps/system_design/improvement_prompt.py
  gpt_all_star/core/steps/system_design/system_design.py
  gpt_all_star/core/steps/ui_design/ui_design.py
  gpt_all_star/locales/ja_JP/ja.po
Labels: documentation, chore

#229 Bump version to 0.0.20 in pyproject.toml
  pyproject.toml
Labels: chore

#231 Update Japanese translation and strings in core/agents/copilot.py
  gpt_all_star/locales/ja_JP/LC_MESSAGES/messages.mo
  gpt_all_star/locales/ja_JP/ja.po
Labels: chore

#232 Bump version to 0.0.21 in pyproject.toml
  pyproject.toml
Labels: chore

#240 Refactor error message formatting in Project class
  gpt_all_star/core/project.py
Labels: bug

#242 Bump version to 0.0.22 in pyproject.toml
  pyproject.toml
Labels: chore
